using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Events;
public class DeliveryDriver : MonoBehaviour
{
    [Header("배달원 설정")]
    public float movespeed = 8f;
    public float rotationSpeed = 10.0f;

    [Header("상태")]
    public float currentMoney = 0;
    public float batteryLevel = 100f;
    public int deliveryCount = 0;

    [System.Serializable]

    public class DriverEvents
    {
        [Header("이동 Event")]
        public UnityEvent OnMoveStarted;
        public UnityEvent OnMoveStoped;

        [Header("상태 변화 Event")]
        public UnityEvent<float> OnMoneyChanged;
        public UnityEvent<float> OnBatteryChanged;
        public UnityEvent<int> OnDeliveryCountChanged;

        [Header("경고 Event")]
        public UnityEvent OnLowBattery;
        public UnityEvent OnLowBatteryEmpty;
        public UnityEvent OnDeliveryCompleted;
    }

    public DriverEvents driveEvents;
    public bool isMoving = false;

    // Start is called before the first frame update
    void Start()
    {
        driveEvents.OnMoneyChanged?.Invoke(currentMoney);
        driveEvents.OnBatteryChanged?.Invoke(batteryLevel);
        driveEvents.OnDeliveryCountChanged?.Invoke(deliveryCount);
    }

    // Update is called once per frame
    void Update()
    {
        HandleMovement();
        UpdateBattery();
    }

    void HandleMovement()
    {
        if(batteryLevel <= 0)
        {
            if (isMoving)
            {

            }
            return;
        }

        float horizontal = Input.GetAxis("Horizontal");
        float vertical = Input.GetAxis("Vertical");

        Vector3 moveDirection = new Vector3(horizontal, 0 , vertical);

        if(moveDirection.magnitude > 0.1f)
        {
            if (!isMoving)
            {
                StartMoving();
            }

            moveDirection = moveDirection.normalized;
            transform.Translate(moveDirection * movespeed * Time.deltaTime, Space.World);

            if(moveDirection != Vector3.zero)
            {
                Quaternion targetRotation = Quaternion.LookRotation(moveDirection);
                transform.rotation = Quaternion.Slerp(transform.rotation, targetRotation, rotationSpeed * Time.deltaTime);
            }
            ChangedBattery(-Time.deltaTime * 3.0f);
        }
        else
        {
            if (isMoving)
            {
                StopMoving();
            }
        }
    }

    void ChangedBattery(float amount)
    {
        float oldBattery = batteryLevel;
        batteryLevel += amount;
        batteryLevel = Mathf.Clamp(batteryLevel, 0, 100);

        driveEvents.OnBatteryChanged?.Invoke(batteryLevel);

        if(oldBattery > 20f && batteryLevel <= 20f)
        {
            driveEvents.OnLowBattery?.Invoke();
        }
        if(oldBattery > 0f && batteryLevel <= 0f)
        {
            driveEvents.OnLowBatteryEmpty?.Invoke();
        }
    }


    void StartMoving()
    {
        isMoving = true;
        driveEvents.OnMoveStarted?.Invoke();
    }

    void StopMoving()
    {
        isMoving = false;
        driveEvents.OnMoveStoped?.Invoke();
    }

    void UpdateBattery()
    {
        if(batteryLevel > 0)
        {
            ChangedBattery(-Time.deltaTime * 0.5f);
        }
    }

    public void AddMoney(float amount)
    {
        currentMoney += amount;
        driveEvents.OnMoneyChanged?.Invoke(currentMoney);
    }

    public void CompleteDelivery()
    {
        deliveryCount++;
        float reward = Random.Range(3000, 8000);

        AddMoney(reward);
        driveEvents.OnDeliveryCountChanged?.Invoke(deliveryCount);
        driveEvents.OnDeliveryCompleted?.Invoke();
    }

    public void ChargeBattery()
    {
        ChangedBattery(100f -  batteryLevel);
    }

    public string GetStatusText()
    {
        return $"돈 : {currentMoney:F0} 원 | 배터리 : {batteryLevel:F1}% | 배달 : {deliveryCount} 건";
    }

    public bool CanMove()
    {
        return batteryLevel > 0;
    }
}
